// helpers/commandDescriptions.js
//
// One-line descriptions for the .help command. Keyed by bare command name
// (no prefix). If a registered command isn't listed here, .help falls back
// to a generic placeholder rather than omitting it — so newly added
// commands still show up, just without a description until one is added
// here.
//
// NOTE: these were written from the command names and their existing menu
// category groupings, not from reading every plugin's full implementation —
// most should be accurate but a few (especially the anime-flavoured FUN
// commands) are best-effort guesses. Worth a skim and a correction pass.

module.exports = {
    ai: "Chat with the bot's main AI assistant.",
    groq: "Chat using the Groq-powered AI engine.",
    gojo: "Chat in Gojo persona/character mode.",
    debug: "Show debug info for troubleshooting AI/bot responses.",
    summon: "Summon a custom AI persona into the chat.",
    read: "Have the AI read and respond to a message or file.",
    imagine: "Generate an AI image from a text prompt.",
    lizzy: "Chat in Lizzy persona/character mode.",
    aizen: "Chat in Aizen persona/character mode.",
    say: "Make the bot speak a message (text-to-speech or persona reply).",
    games: "List and launch available mini-games.",
    ttt: "Play Tic-Tac-Toe against another member or the bot.",
    rps: "Play Rock-Paper-Scissors.",
    guess: "Play a number/word guessing game.",
    vault8: "Play the Vault8 puzzle/game.",
    quiz: "Start a trivia quiz round.",
    charade: "Play a charades-style guessing game.",
    anagram: "Play an anagram-unscrambling game.",
    wcg: "Play Word Chain Game.",
    millionaire: "Play a Who-Wants-to-Be-a-Millionaire-style quiz.",
    torf: "Play True or False.",
    pvp: "Start a player-vs-player duel/game.",
    escape: "Play an escape-room style puzzle game.",
    mute: "Restrict a member from sending messages in the group.",
    unmute: "Lift a mute restriction on a member.",
    kick: "Remove a member from the group.",
    promote: "Promote a member to group admin.",
    demote: "Remove admin rights from a member.",
    tagall: "Mention every member of the group.",
    tag: "Tag specific members with a message.",
    link: "Get the group's invite link.",
    antilink: "Toggle automatic removal of links posted by non-admins.",
    admins: "List the group's current admins.",
    antitag: "Toggle protection against mass-tag abuse.",
    antibot: "Toggle blocking of other bots in the group.",
    warn: "Issue a warning to a member.",
    welcome: "Configure the welcome message for new members.",
    goodbye: "Configure the farewell message for leaving members.",
    poll: "Create a poll in the group.",
    antigm: "Toggle protection against unauthorized group metadata/setting changes.",
    gclog: "Toggle logging of group activity (joins, leaves, admin changes).",
    antispam: "Toggle automatic action against message spam in the group.",
    silence: "Temporarily silence the group (owner/admin only messages).",
    gcalerts: "Toggle group alert notifications (joins/leaves/etc).",
    antipromote: "Toggle protection against unauthorized promotions.",
    antidemote: "Toggle protection against unauthorized demotions.",
    overkill: "Apply an aggressive combined moderation preset.",
    antijoin: "Toggle restrictions on new members joining.",
    gfilter: "Configure a group-specific word/content filter.",
    search: "AI-powered command finder — describe what you need in plain words.",
    track: "Track a package, order, or similar reference number.",
    getpp: "Fetch a user's profile picture.",
    setname: "Change the bot's display name.",
    save: "Save a quoted message or media for later.",
    tostatus: "Repost a quoted message/media as the bot's status update.",
    fw: "Forward a message.",
    presence: "Configure how the bot's presence (online/typing) behaves.",
    autotyping: "Toggle the bot showing a typing indicator before replying.",
    autorecording: "Toggle the bot showing a recording indicator before voice replies.",
    alwaysonline: "Keep the bot's account shown as always online.",
    autoread: "Toggle automatically marking incoming messages as read.",
    antidelete: "Toggle re-posting messages that were deleted by their sender.",
    antiviewonce: "Toggle capturing view-once media before it disappears.",
    antibug: "Toggle protection against known message-based crash/bug exploits.",
    clear: "Clear the bot's chat/media cache.",
    autoviewstatus: "Toggle automatically viewing contacts' status updates.",
    statusemoji: "Set the emoji reaction used on auto-viewed statuses.",
    autoreactstatus: "Toggle automatically reacting to contacts' status updates.",
    block: "Block a user.",
    unblock: "Unblock a user.",
    aza: "Run the Aza utility command.",
    time: "Show the current time (optionally for another timezone).",
    weather: "Get the current weather for a location.",
    device: "Show what device/platform a user is on.",
    ss: "Take a screenshot of a webpage.",
    calc: "Evaluate a math expression.",
    trt: "Translate text between languages.",
    spam: "Send a message repeatedly (use responsibly).",
    pfilter: "Configure a personal/private word filter.",
    filters: "List currently configured filters.",
    delfilter: "Delete a configured filter.",
    play: "Search and download a song by name.",
    yt: "Download a YouTube video.",
    img: "Search and download images.",
    song: "Download an audio track.",
    fb: "Download a Facebook video.",
    tt: "Download a TikTok video.",
    mediafire: "Download a file from a Mediafire link.",
    apk: "Search and download an Android APK.",
    shazam: "Identify a song from an audio clip.",
    lyrics: "Fetch lyrics for a song.",
    gdrive: "Download a file from a Google Drive link.",
    gitclone: "Download a GitHub repository as a zip.",
    pinterest: "Search and download Pinterest images.",
    spotify: "Download a track from a Spotify link.",
    web: "Fetch/download content from a webpage.",
    tgs: "Download/convert a Telegram sticker.",
    ig: "Download an Instagram post/reel.",
    bankai: "Trigger a Bleach-style Bankai roleplay animation.",
    'dom-exp': "Trigger a Jujutsu Kaisen-style Domain Expansion roleplay animation.",
    wyr: "Get a Would-You-Rather question.",
    joke: "Get a random joke.",
    insult: "Send a playful insult at a tagged member.",
    roast: "Roast a tagged member.",
    ship: "Ship two members together with a compatibility score.",
    wed: "Roleplay a wedding between two members.",
    propose: "Roleplay a marriage proposal to a member.",
    askout: "Roleplay asking a member out.",
    'hollow-purple': "Trigger a Jujutsu Kaisen-style Hollow Purple roleplay animation.",
    hack: "Roleplay a fake hacking animation/sequence.",
    arrest: "Roleplay arresting a tagged member.",
    liedetector: "Run a joke lie-detector on a message.",
    rizz: "Get a random pickup line.",
    speech: "Generate a dramatic roleplay speech/monologue.",
    slap: "Slap a tagged member (roleplay action).",
    kill: "Roleplay killing a tagged member.",
    kiss: "Kiss a tagged member (roleplay action).",
    hug: "Hug a tagged member (roleplay action).",
    dance: "Send a dance animation/gif.",
    aura: "Rate or generate a member's aura score.",
    lol: "Send a laughing reaction/gif.",
    prefix: "Show a reminder of the current command prefix.",
    diagnose: "Run bot self-diagnostics.",
    update: "Pull the latest code updates from GitHub.",
    mode: "Switch the bot between public and private mode.",
    setsudo: "Grant a user sudo (elevated) access.",
    delsudo: "Revoke a user's sudo access.",
    addowner: "Add a new bot owner.",
    delowner: "Remove a bot owner.",
    restart: "Restart the bot's connection.",
    shutdown: "Shut the bot down.",
    ban: "Ban a user from using the bot.",
    unban: "Unban a user.",
    afk: "Set an away-from-keyboard status/message.",
    setvar: "Configure a runtime variable (e.g. prefix).",
    settings: "View current bot settings.",
    antipm: "Toggle blocking/limiting direct messages to the bot.",
    reminder: "Set a reminder.",
    ping: "Check the bot's response speed (animated).",
    alive: "Check that the bot is online.",
    delete: "Delete a quoted bot message.",
    tdelete: "Delete a message after a timer.",
    autoreact: "Toggle automatic emoji reactions to messages.",
    speed: "Check bot latency (prefixless — just type \"Speed\").",
    sticker: "Convert an image/video into a sticker.",
    crop: "Crop a sticker/image.",
    take: "Re-brand/take ownership of a sticker's pack info.",
    smeme: "Make a meme sticker with top/bottom text.",
    packname: "Set the default sticker pack name/author.",
    fixpack: "Fix a broken sticker's pack metadata.",
    unpack: "Extract an image/video back out of a sticker.",
    tourl: "Upload media and get a direct URL.",
    kamui: "Trigger a Naruto-style Kamui roleplay animation.",
    addnote: "Save a personal note.",
    delnote: "Delete a saved note.",
    getnotes: "List your saved notes.",
    toimg: "Convert a sticker back into an image.",
    tomp3: "Convert audio/video to MP3.",
    tomp4: "Convert media to MP4.",
    binary: "Convert text to/from binary.",
    ocr: "Extract text from an image.",
    qr: "Generate a QR code.",
    readqr: "Read/decode a QR code from an image.",
    qty: "Convert a quantity/unit.",
    currency: "Convert between currencies.",
    menu: "Show the plain text menu.",
    list: "Show the plain text menu (alias of .menu).",
    menu2: "Show the category picker menu (single message, native list).",
    list2: "Show the category picker menu (alias of .menu2).",
    menu3: "Show the per-category card menu (multiple messages).",
    list3: "Show the per-category card menu (alias of .menu3).",
    help: "Show this list of every command with a description.",
    commands: "Show this list of every command with a description (alias of .help).",
};
