// helpers/commandDescriptions.js
//
// One-line descriptions for the .help command. Keyed by bare command name
// (no prefix), sorted A-Z. If a registered command isn't listed here, .help
// falls back to a generic placeholder rather than omitting it — so newly
// added commands still show up, just without a description until one is
// added here.
//
// NOTE: most of these were written from the command names and their
// existing menu category groupings, not from reading every plugin's full
// implementation, so a few are still best-effort guesses rather than
// confirmed behavior. Corrected so far: aza, summon.

module.exports = {
    // ─── Added: previously undocumented commands, written from their
    // actual plugin code rather than guessed from category groupings. ───
    adapt: "Reprocess a replied image/video at high quality. (adapt-high)",
    'adapt-low': "Reprocess a replied image/video at low quality.",
    'adapt-mid': "Reprocess a replied image/video at medium quality.",
    warp: "AI-edit a replied image from a text prompt.",
    alien: "Show a random Ben 10 alien's bio, powers, and weaknesses.",
    gaycheck: "Randomly 'scan' a user and joke-rate them gay or not.",
    gay: "Add a user to the group's joke gay list (owner/sudo/dev only).",
    antigay: "Toggle auto-action against users on the gay list.",
    gaylist: "Show everyone currently on the gay list.",
    catbox: "Download a file or full album from a catbox.moe link.",
    facebook: "Download a Facebook video. (fb)",
    tiktok: "Download a TikTok video. (tt)",
    youtube: "Download a YouTube video. (yt)",
    instagram: "Download Instagram media. (ig)",
    xdl: "Download a Twitter/X video or image. (x)",
    obf: "Obfuscate JavaScript code at low/medium/high strength.",
    xvid: "Search a video site and pick a result to get its link.",
    emojimix: "Blend two emojis into one sticker. (emix)",
    laugh: "Send a laughing reaction/gif. (lol, xd)",
    farm: "Rate or generate a member's aura score. (aura)",
    'domain-expansion': "Trigger a JJK-style Domain Expansion animation. (dom-exp)",
    'purple-tech': "Trigger Gojo's Hollow Purple animation. (hollow-purple)",
    info: "Show a target user's WhatsApp profile info card.",
    asst: "Show which chatbot personas (Gojo/Aizen) are active in this chat.",
    news: "Toggle automatic anime news alerts for this group.",
    remindme: "Set a personal reminder to fire after a delay (e.g. 10m, 2h).",
    setpp: "Update the bot's profile picture from a replied image (use 'gc' for the group's picture instead).",
    setgpp: "Update the current group's profile picture from a replied image. (setpp gc)",
    vars: "List every variable that can be changed with .setvar.",
    owner: "List the bot's registered owners, secondary owners, and sudo users.",
    logs: "Show the bot's most recent console log lines.",
    allow: "Grant a user or the whole chat access to specific commands in restricted/private mode.",
    disallow: "Revoke a user's or chat's access to specific commands.",
    'disallow-all': "Clear all custom command permissions for a user or chat. (disallowall)",
    sp: "Send a native WhatsApp sticker-pack card.",
    sp2: "Send 10 random GIFs (converted to video) from Klipy.",
    addbot: "Pair another WhatsApp number in as a sub-bot session.",
    delbot: "Remove an active sub-bot session.",
    listbots: "List all currently active sub-bot sessions.",
    script: "Show bot info with buttons for the GitHub repo link and a ZIP download. (sc, repo)",
    gcinfo: "Show detailed metadata and stats about the current group.",
    archive: "Archive the current chat.",
    unarchive: "Unarchive the current chat.",
    calculator: "Evaluate a math expression. (calc)",
    translate: "Translate text. (trt)",
    tojid: "Post replied media/text to a specific group's status by JID.",
    vv: "Manually decrypt and repost a replied View-Once message.",
    setcmd: "Map a command to trigger from a replied sticker.",
    delcmd: "Remove a sticker-to-command mapping.",
    silent_decrypter: "Prefixless: silently DMs a decrypted copy of a replied View-Once message to the sender when an owner/sudo/dev sends a trigger word or emoji.",
    user: "Show a tappable contact card (photo + message button) for a user.",
    id: "Show a user's or group's resolved JID and LID.",
    dev: "Show the bot developer's contact card.",
    uriel: "Prefixless AI persona command, restricted to owners/sudo/devs.",
    aza: "Show saved bank account details, or run `.aza set` to configure them.",
    'alive-set': "Configure the bot's custom .alive message/media template.",
    ping2: "Alternate animated latency check.",
    notes: "Show the sticky-notes dashboard and instructions for this chat.",
    getnote: "Retrieve a saved note by title.",
    uptime: "Show how long the bot process has been running. (runtime)",
    card: "Manually spawn a Yu-Gi-Oh card to claim in this group.",
    claim: "Claim the currently spawned Yu-Gi-Oh card. (upgrade, cardclaim)",
    deck: "Show your current Yu-Gi-Oh deck.",
    collection: "Show your Yu-Gi-Oh card collection binder. (coll, binder)",
    'to-coll': "Move card(s) from your deck into your collection. (tocoll, toco)",
    'to-deck': "Move card(s) from your collection into your deck. (todeck, tode)",
    cardspawn: "Toggle automatic periodic Yu-Gi-Oh card spawns in this group.",
    levelup: "Toggle level-up milestone announcements for this group.",
    ranks: "Show all activity rank tiers and their message thresholds.",
    rank: "Show a member's current activity rank. (level)",
    leaderboard: "Show the group's top members by tracked messages. (lb)",
    creategc: "Create a new WhatsApp group.",
    kickall: "Remove all non-admin members from the group (owner/sudo/dev only).",
    stopkickall: "Stop an in-progress .kickall run.",
    tkick: "Schedule a member to be auto-kicked after a set duration.",
    join: "Fetch a group's invite link or JID from a link/message (owner/dev only).",
    exit: "Make the bot leave a group. (leave)",
    gcstatus: "Post a replied message directly to the group's status.",
    poll: "Create a poll: `.poll Question? (Option1/Option2)`.",
    htag: "Tag every member with a hidden/invisible mention, then delete the trigger. (ghost)",
    spamtag: "Repeatedly tag group members with a given text.",
    gmode: "Show an interactive group mode configuration panel for admins.",
    gcjid: "Show this group's JID.",
    active: "List members who have been active in the group today.",
    inactive: "List members who have not been active in the group today.",
    msgs: "Show message-tracking stats for this group.",
    unmute: "Reopen the group to everyone. (open, unlock)",
    close: "Restrict the group to admins-only. (lock)",
    silence: "Temporarily auto-delete every message from a specific user.",
    unsilence: "Remove a silence restriction from a user.",
    delspam: "Clear a member's accumulated spam-warning strikes.",
    infinity: "Alias of antilink — toggle automatic removal of links posted by non-admins.",
    activegames: "Alias of games.",
    'adapt-high': "Reprocess a replied image/video at high quality. (adapt)",
    aizen_chat: "Internal handler for Aizen persona chat replies (triggered by saying 'aizen' in an enabled chat, not typed directly).",
    gojo_chat: "Internal handler for Gojo persona chat replies (triggered by saying 'gojo' in an enabled chat, not typed directly).",
    anagram_mode: "Configure the anagram game's word list/difficulty settings.",
    anagrams: "Alias of anagram.",
    antigcstatus: "Toggle blocking non-admin group status posts.",
    autors: "Alias of autoreactstatus.",
    autovs: "Alias of autoviewstatus.",
    bite: "Roleplay biting a tagged member.",
    dap: "Roleplay dapping up a tagged member.",
    hifive: "Roleplay high-fiving a tagged member.",
    kik: "Roleplay kicking a tagged member (for laughs, not a real group kick).",
    poke: "Roleplay poking a tagged member.",
    punch: "Roleplay punching a tagged member.",
    charades: "Alias of charade.",
    sharade: "Alias of charade.",
    sharades: "Alias of charade.",
    demo: "Alias of demotion.",
    demotion: "Toggle alerts announcing when a member is demoted.",
    promo: "Alias of promotion.",
    promotion: "Toggle alerts announcing when a member is promoted.",
    emix: "Alias of emojimix.",
    forward: "Alias of fw.",
    quantity: "Convert a quantity between units using AI. (qty)",
    s: "Alias of sticker.",
    setgoodbye: "Set and enable a custom farewell message template.",
    setwelcome: "Set and enable a custom welcome message template.",
    steal: "Alias of take.",
    tictactoe: "Alias of ttt.",
    ttt_mode: "Configure Tic-Tac-Toe game mode/settings.",
    url: "Alias of tourl.",
    wordchain: "Alias of wcg.",
    wrg: "Alias of wcg.",
    x: "Download a Twitter/X video or image. (xdl)",
    pvp_lobby_accept: "Internal button handler: accepts a pending PvP battle challenge.",
    // Pure aliases — same behavior as their main command, listed separately
    // here only because they're registered under their own name too.
    sc: "Alias of script.",
    repo: "Alias of script.",
    xd: "Alias of lol.",
    invite: "Alias of link.",
    gclink: "Alias of link.",
    open: "Alias of mute (opens the group back up).",
    unlock: "Alias of mute (opens the group back up).",
    lock: "Alias of mute (closes the group to admins-only).",
    lockjoin: "Alias of antijoin.",
    lb: "Alias of leaderboard.",
    level: "Alias of rank.",
    leave: "Alias of exit.",
    ghost: "Alias of htag.",
    upgrade: "Alias of claim.",
    cardclaim: "Alias of claim.",
    coll: "Alias of collection.",
    binder: "Alias of collection.",
    tocoll: "Alias of to-coll.",
    toco: "Alias of to-coll.",
    todeck: "Alias of to-deck.",
    tode: "Alias of to-deck.",
    disallowall: "Alias of disallow-all.",
    runtime: "Alias of uptime.",
    del: "Alias of delete.",
    dlt: "Alias of delete.",
    tdel: "Alias of tdelete.",
    tdlt: "Alias of tdelete.",
    'add-owner': "Alias of addowner.",
    'del-owner': "Alias of delowner.",
    addnote: "Save a personal note.",
    addowner: "Add a new bot owner.",
    admins: "List the group's current admins.",
    afk: "Set an away-from-keyboard status/message.",
    ai: "Chat with the bot's main AI assistant.",
    aizen: "Chat in Aizen persona/character mode.",
    alive: "Check that the bot is online.",
    alwaysonline: "Keep the bot's account shown as always online.",
    anagram: "Play an anagram-unscrambling game.",
    antibot: "Toggle blocking of other bots in the group.",
    antibug: "Toggle protection against known message-based crash/bug exploits.",
    antidelete: "Toggle re-posting messages that were deleted by their sender.",
    antidemote: "Toggle protection against unauthorized demotions.",
    antigm: "Toggle protection against unauthorized group metadata/setting changes.",
    antijoin: "Toggle restrictions on new members joining.",
    antilink: "Toggle automatic removal of links posted by non-admins.",
    antipm: "Toggle blocking/limiting direct messages to the bot.",
    antipromote: "Toggle protection against unauthorized promotions.",
    antispam: "Toggle automatic action against message spam in the group.",
    antitag: "Toggle protection against mass-tag abuse.",
    antiviewonce: "Toggle capturing view-once media before it disappears.",
    apk: "Search and download an Android APK.",
    arrest: "Roleplay arresting a tagged member.",
    askout: "Roleplay asking a member out.",
    aura: "Rate or generate a member's aura score.",
    autoreact: "Toggle automatic emoji reactions to messages.",
    autoreactstatus: "Toggle automatically reacting to contacts' status updates.",
    autoread: "Toggle automatically marking incoming messages as read.",
    autorecording: "Toggle the bot showing a recording indicator before voice replies.",
    autotyping: "Toggle the bot showing a typing indicator before replying.",
    autoviewstatus: "Toggle automatically viewing contacts' status updates.",
    aza: "Check bank/account balance details.",
    ban: "Ban a user from using the bot.",
    bankai: "Look up a Bleach character's Bankai name and image. No name given = random pick.",
    binary: "Convert text to/from binary.",
    block: "Block a user.",
    calc: "Evaluate a math expression.",
    charade: "Play a charades-style guessing game.",
    clear: "Clear the bot's chat/media cache.",
    commands: "Show this list of every command with a description (alias of .help).",
    crop: "Crop a sticker/image.",
    currency: "Convert between currencies.",
    dance: "Send a dance animation/gif.",
    debug: "Show debug info for troubleshooting AI/bot responses.",
    delete: "Delete a quoted bot message.",
    delfilter: "Delete a configured filter.",
    delnote: "Delete a saved note.",
    delowner: "Remove a bot owner.",
    delsudo: "Revoke a user's sudo access.",
    demote: "Remove admin rights from a member.",
    device: "Show what device/platform a user is on.",
    diagnose: "Run bot self-diagnostics.",
    'dom-exp': "Trigger a Jujutsu Kaisen-style Domain Expansion roleplay animation.",
    escape: "Play an escape-room style puzzle game.",
    fb: "Download a Facebook video.",
    filters: "List currently configured filters.",
    fixpack: "Fix a broken sticker's pack metadata.",
    fw: "Forward a message.",
    games: "List and launch available mini-games.",
    gcalerts: "Toggle group alert notifications (joins/leaves/etc).",
    gclog: "Toggle logging of group activity (joins, leaves, admin changes).",
    gdrive: "Download a file from a Google Drive link.",
    getnotes: "List your saved notes.",
    getpp: "Fetch a user's profile picture.",
    gfilter: "Configure a group-specific word/content filter.",
    gitclone: "Download a GitHub repository as a zip.",
    gojo: "Chat in Gojo persona/character mode.",
    goodbye: "Configure the farewell message for leaving members.",
    groq: "Chat using the Groq-powered AI engine.",
    guess: "Play a number/word guessing game.",
    hack: "Roleplay a fake hacking animation/sequence.",
    help: "Show this list of every command with a description.",
    'hollow-purple': "Trigger a Jujutsu Kaisen-style Hollow Purple roleplay animation.",
    hug: "Hug a tagged member (roleplay action).",
    ig: "Download an Instagram post/reel.",
    imagine: "Generate an AI image from a text prompt.",
    img: "Search and download images.",
    insult: "Send a playful insult at a tagged member.",
    joke: "Get a random joke.",
    kamui: "Trigger a Naruto-style Kamui roleplay animation.",
    kick: "Remove a member from the group.",
    kill: "Roleplay killing a tagged member.",
    kiss: "Kiss a tagged member (roleplay action).",
    liedetector: "Run a joke lie-detector on a message.",
    link: "Get the group's invite link.",
    list: "Show the plain text menu (alias of .menu).",
    list2: "Show the category picker menu (alias of .menu2).",
    list3: "Show the per-category card menu (alias of .menu3).",
    lizzy: "Chat in Lizzy persona/character mode.",
    lol: "Send a laughing reaction/gif.",
    lyrics: "Fetch lyrics for a song.",
    mediafire: "Download a file from a Mediafire link.",
    menu: "Show the plain text menu.",
    menu2: "Show the category picker menu (single message, native list).",
    menu3: "Show the per-category card menu (multiple messages).",
    millionaire: "Play a Who-Wants-to-Be-a-Millionaire-style quiz.",
    mode: "Switch the bot between public and private mode.",
    mute: "Restrict a member from sending messages in the group.",
    ocr: "Extract text from an image.",
    overkill: "Apply an aggressive combined moderation preset.",
    packname: "Set the default sticker pack name/author.",
    pfilter: "Configure a personal/private word filter.",
    ping: "Check the bot's response speed (animated).",
    pinterest: "Search and download Pinterest images.",
    play: "Search and download a song by name.",
    poll: "Create a poll in the group.",
    prefix: "Show a reminder of the current command prefix.",
    presence: "Configure how the bot's presence (online/typing) behaves.",
    promote: "Promote a member to group admin.",
    propose: "Roleplay a marriage proposal to a member.",
    pvp: "Start a player-vs-player duel/game.",
    qr: "Generate a QR code.",
    qty: "Convert a quantity/unit.",
    quiz: "Start a trivia quiz round.",
    read: "Have the AI read and respond to a message or file.",
    readqr: "Read/decode a QR code from an image.",
    reminder: "Set a reminder.",
    restart: "Restart the bot's connection.",
    rizz: "Get a random pickup line.",
    roast: "Roast a tagged member.",
    rps: "Play Rock-Paper-Scissors.",
    save: "Save a quoted message or media for later.",
    say: "Make the bot speak a message (text-to-speech or persona reply).",
    search: "AI-powered command finder — describe what you need in plain words.",
    setname: "Change the bot's display name.",
    setsudo: "Grant a user sudo (elevated) access.",
    settings: "View current bot settings.",
    setvar: "Configure a runtime variable (e.g. prefix).",
    shazam: "Identify a song from an audio clip.",
    ship: "Ship two members together with a compatibility score.",
    shutdown: "Shut the bot down.",
    silence: "Temporarily silence the group (owner/admin only messages).",
    slap: "Slap a tagged member (roleplay action).",
    smeme: "Make a meme sticker with top/bottom text.",
    song: "Download an audio track.",
    spam: "Send a message repeatedly (use responsibly).",
    speech: "Generate a dramatic roleplay speech/monologue.",
    speed: "Check bot latency (prefixless — just type \\\"Speed\\\").",
    spotify: "Download a track from a Spotify link.",
    ss: "Take a screenshot of a webpage.",
    statusemoji: "Set the emoji reaction used on auto-viewed statuses.",
    sticker: "Convert an image/video into a sticker.",
    summon: "Summon a fictional character into the chat.",
    tag: "Tag specific members with a message.",
    tagall: "Mention every member of the group.",
    take: "Re-brand/take ownership of a sticker's pack info.",
    tdelete: "Delete a message after a timer.",
    tgs: "Download/convert a Telegram sticker.",
    time: "Show the current time (optionally for another timezone).",
    toimg: "Convert a sticker back into an image.",
    tomp3: "Convert audio/video to MP3.",
    tomp4: "Convert media to MP4.",
    torf: "Play True or False.",
    tostatus: "Repost a quoted message/media as the bot's status update.",
    tourl: "Upload media and get a direct URL.",
    track: "Track a package, order, or similar reference number.",
    trt: "Translate text between languages.",
    tt: "Download a TikTok video.",
    ttt: "Play Tic-Tac-Toe against another member or the bot.",
    unban: "Unban a user.",
    unblock: "Unblock a user.",
    unmute: "Lift a mute restriction on a member.",
    unpack: "Extract an image/video back out of a sticker.",
    update: "Pull the latest code updates from GitHub.",
    vault8: "Play the Vault8 puzzle/game.",
    warn: "Issue a warning to a member.",
    wcg: "Play Word Chain Game.",
    weather: "Get the current weather for a location.",
    web: "Fetch/download content from a webpage.",
    wed: "Roleplay a wedding between two members.",
    welcome: "Configure the welcome message for new members.",
    wyr: "Get a Would-You-Rather question.",
    yt: "Download a YouTube video.",
};
